import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import { formatPHPFromCentavos, formatPeriodLabel, formatPaymentMethod } from './financeUtils';

interface GenerateFinanceReportInput {
  organizationName?: string;
  reportTitle?: string;
  dateRangeLabel: string;
  generatedBy: string;
  duesPeriods: Array<{
    period_label: string;
    member_name: string;
    voice_part?: string | null;
    effective_due_centavos: number;
    total_paid_centavos: number;
    remaining_balance_centavos: number;
    is_fully_paid: boolean;
  }>;
  payments: Array<{
    paid_at: string;
    member_name: string;
    amount_centavos: number;
    method: string;
    reference?: string | null;
    period_label: string;
    is_voided: boolean;
  }>;
  contributions: Array<{
    contributed_at: string;
    campaign_title: string;
    contributor_name: string;
    amount_centavos: number;
    method: string;
    is_voided: boolean;
  }>;
}

export async function generateFinancialStatementPdf(input: GenerateFinanceReportInput): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const primaryColor = rgb(0.043, 0.302, 0.141); // #0b4d24
  const darkTextColor = rgb(0.1, 0.1, 0.1);
  const mutedTextColor = rgb(0.4, 0.4, 0.4);
  const tableBorderColor = rgb(0.85, 0.85, 0.85);
  const headerBgColor = rgb(0.95, 0.97, 0.95);

  let page = pdfDoc.addPage([595.28, 841.89]); // A4 portrait
  const { width, height } = page.getSize();
  const margin = 40;
  let y = height - margin;

  // Header Banner
  page.drawRectangle({
    x: margin,
    y: y - 55,
    width: width - margin * 2,
    height: 55,
    color: primaryColor,
  });

  page.drawText(input.organizationName || 'CHOIR COLLECTIVE', {
    x: margin + 16,
    y: y - 22,
    size: 14,
    font: fontBold,
    color: rgb(1, 1, 1),
  });

  page.drawText(input.reportTitle || 'TREASURER FINANCIAL & SINKING FUND STATEMENT', {
    x: margin + 16,
    y: y - 42,
    size: 9,
    font: fontRegular,
    color: rgb(0.9, 0.9, 0.9),
  });

  y -= 70;

  // Metadata Row
  page.drawText(`Date Range: ${input.dateRangeLabel}`, {
    x: margin,
    y,
    size: 8.5,
    font: fontBold,
    color: darkTextColor,
  });

  page.drawText(`Generated By: ${input.generatedBy} on ${new Date().toLocaleDateString('en-PH')}`, {
    x: width - margin - 220,
    y,
    size: 8.5,
    font: fontRegular,
    color: mutedTextColor,
  });

  y -= 25;

  // Financial KPI Metrics Box
  const totalDuesCollected = input.payments
    .filter((p) => !p.is_voided)
    .reduce((sum, p) => sum + p.amount_centavos, 0);

  const totalSolicitationsRaised = input.contributions
    .filter((c) => !c.is_voided)
    .reduce((sum, c) => sum + c.amount_centavos, 0);

  const grandTotal = totalDuesCollected + totalSolicitationsRaised;

  const boxWidth = (width - margin * 2 - 20) / 3;
  const metrics = [
    { label: 'Sinking Fund Dues', value: formatPHPFromCentavos(totalDuesCollected) },
    { label: 'Solicitations Raised', value: formatPHPFromCentavos(totalSolicitationsRaised) },
    { label: 'Total Inflow', value: formatPHPFromCentavos(grandTotal) },
  ];

  metrics.forEach((m, idx) => {
    const boxX = margin + idx * (boxWidth + 10);
    page.drawRectangle({
      x: boxX,
      y: y - 42,
      width: boxWidth,
      height: 42,
      color: headerBgColor,
      borderColor: tableBorderColor,
      borderWidth: 1,
    });

    page.drawText(m.label, {
      x: boxX + 10,
      y: y - 16,
      size: 7.5,
      font: fontRegular,
      color: mutedTextColor,
    });

    page.drawText(m.value, {
      x: boxX + 10,
      y: y - 34,
      size: 11,
      font: fontBold,
      color: primaryColor,
    });
  });

  y -= 60;

  // Table 1: Recent Sinking Fund Payments
  page.drawText('1. SINKING FUND COLLECTION TRANSACTIONS', {
    x: margin,
    y,
    size: 9.5,
    font: fontBold,
    color: primaryColor,
  });

  y -= 14;

  // Table Headers
  const colX = [margin, margin + 70, margin + 200, margin + 270, margin + 340, margin + 420];
  page.drawRectangle({
    x: margin,
    y: y - 16,
    width: width - margin * 2,
    height: 16,
    color: headerBgColor,
  });

  const headers = ['Date', 'Member Name', 'Period', 'Method', 'Reference', 'Amount'];
  headers.forEach((h, i) => {
    page.drawText(h, {
      x: colX[i] + 4,
      y: y - 12,
      size: 7.5,
      font: fontBold,
      color: darkTextColor,
    });
  });

  y -= 18;

  const validPayments = input.payments.slice(0, 25); // Limit per page view
  for (const p of validPayments) {
    if (y < 60) {
      page = pdfDoc.addPage([595.28, 841.89]);
      y = height - margin;
    }

    const isVoid = p.is_voided;
    const rowColor = isVoid ? mutedTextColor : darkTextColor;
    const dateStr = p.paid_at ? new Date(p.paid_at).toLocaleDateString('en-PH') : '—';

    page.drawText(dateStr, { x: colX[0] + 4, y, size: 7.5, font: fontRegular, color: rowColor });
    page.drawText(p.member_name.substring(0, 24), { x: colX[1] + 4, y, size: 7.5, font: fontRegular, color: rowColor });
    page.drawText(formatPeriodLabel(p.period_label).substring(0, 14), { x: colX[2] + 4, y, size: 7.5, font: fontRegular, color: rowColor });
    page.drawText(formatPaymentMethod(p.method), { x: colX[3] + 4, y, size: 7.5, font: fontRegular, color: rowColor });
    page.drawText((p.reference || '—').substring(0, 12), { x: colX[4] + 4, y, size: 7.5, font: fontRegular, color: rowColor });
    page.drawText(
      `${isVoid ? '[VOID] ' : ''}${formatPHPFromCentavos(p.amount_centavos)}`,
      { x: colX[5] + 4, y, size: 7.5, font: isVoid ? fontRegular : fontBold, color: isVoid ? rgb(0.8, 0.2, 0.2) : darkTextColor }
    );

    y -= 14;
  }

  y -= 15;

  // Table 2: Solicitations Contributions
  if (y < 120) {
    page = pdfDoc.addPage([595.28, 841.89]);
    y = height - margin;
  }

  page.drawText('2. SOLICITATIONS & SPECIAL FUNDRAISING CONTRIBUTIONS', {
    x: margin,
    y,
    size: 9.5,
    font: fontBold,
    color: primaryColor,
  });

  y -= 14;

  const solColX = [margin, margin + 70, margin + 200, margin + 340, margin + 420];
  page.drawRectangle({
    x: margin,
    y: y - 16,
    width: width - margin * 2,
    height: 16,
    color: headerBgColor,
  });

  const solHeaders = ['Date', 'Campaign', 'Contributor', 'Method', 'Amount'];
  solHeaders.forEach((h, i) => {
    page.drawText(h, {
      x: solColX[i] + 4,
      y: y - 12,
      size: 7.5,
      font: fontBold,
      color: darkTextColor,
    });
  });

  y -= 18;

  const validContributions = input.contributions.slice(0, 20);
  if (validContributions.length === 0) {
    page.drawText('No solicitation contributions recorded for this period.', {
      x: margin + 4,
      y,
      size: 7.5,
      font: fontRegular,
      color: mutedTextColor,
    });
    y -= 14;
  } else {
    for (const c of validContributions) {
      if (y < 60) {
        page = pdfDoc.addPage([595.28, 841.89]);
        y = height - margin;
      }

      const isVoid = c.is_voided;
      const rowColor = isVoid ? mutedTextColor : darkTextColor;
      const dateStr = c.contributed_at ? new Date(c.contributed_at).toLocaleDateString('en-PH') : '—';

      page.drawText(dateStr, { x: solColX[0] + 4, y, size: 7.5, font: fontRegular, color: rowColor });
      page.drawText(c.campaign_title.substring(0, 24), { x: solColX[1] + 4, y, size: 7.5, font: fontRegular, color: rowColor });
      page.drawText(c.contributor_name.substring(0, 26), { x: solColX[2] + 4, y, size: 7.5, font: fontRegular, color: rowColor });
      page.drawText(formatPaymentMethod(c.method), { x: solColX[3] + 4, y, size: 7.5, font: fontRegular, color: rowColor });
      page.drawText(
        `${isVoid ? '[VOID] ' : ''}${formatPHPFromCentavos(c.amount_centavos)}`,
        { x: solColX[4] + 4, y, size: 7.5, font: isVoid ? fontRegular : fontBold, color: isVoid ? rgb(0.8, 0.2, 0.2) : darkTextColor }
      );

      y -= 14;
    }
  }

  // Footer Signatures
  if (y < 80) {
    page = pdfDoc.addPage([595.28, 841.89]);
    y = height - margin;
  }

  y -= 30;
  page.drawLine({
    start: { x: margin, y },
    end: { x: margin + 160, y },
    thickness: 1,
    color: darkTextColor,
  });

  page.drawText('Prepared by / Treasurer', {
    x: margin,
    y: y - 12,
    size: 7.5,
    font: fontRegular,
    color: darkTextColor,
  });

  page.drawLine({
    start: { x: width - margin - 160, y },
    end: { x: width - margin, y },
    thickness: 1,
    color: darkTextColor,
  });

  page.drawText('Noted by / Choir Director', {
    x: width - margin - 160,
    y: y - 12,
    size: 7.5,
    font: fontRegular,
    color: darkTextColor,
  });

  return pdfDoc.save();
}
